type Tokens {
  auth0: String
  github: String
  imgur: String
  google: String
}

type ImgurAccount {
  id: String!
  name: String
  avatar: String
  bio: String
  city: String
  country: String
  timezone: String
}

type GoogleAccount {
  id: String!
  email: String
  email_verified: Boolean
  name: String
  avatar: String
  city: String
  country: String
  timezone: String
}

type GitHubAccount {
  id: String!
  email: String
  email_verified: Boolean
  name: String
  avatar: String
  bio: String
  city: String
  country: String
  timezone: String
  hireable: String
  profile: String
}

type RequestorMirror {
  id: String
  ip: String
  token: String
  email: String
  github: GitHubAccount
  imgur: ImgurAccount
  google: GoogleAccount
}

type CreatorAccount {
  requestor: RequestorMirror!
  creator: Creator
  authentication: Tokens
}

# Github Integration
type VueComponent {
  oid: String!
  name: String
  vue: String
  template: String
  script: String
  query: String
}

# Imgur Integration
type ImgurAlbum {
  id: String!
  link: String!
  title: String
  description: String
  deletehash: String
  cover: String
  privacy: String
  images: [ImgurImage]
  images_count: Int
  order: String
  datetime: Date
}

type ImgurImage {
  id: String!
  link: String!
  title: String
  description: String
  deletehash: String
  datetime: Date
}

# Google Integration
type Docule {
  id: String!
  link: String!
  title: String
}

type Creator {
  id: Int!
  handle: String!
  email: String!
  subs: [String]
  verified: Boolean
  posts: [Post!]
  template: Template!
  permissions: [Permissions!]
  interactions: [Interaction!]
  templates: [Template]
  name: String!
  avatar: String!
  activeTemplate: Template
  banner: String
  status: String
  bio: String
  website: String
  location: String
  chosenday: String
  joined: String
  createdAt: Date
  updatedAt: Date
}

type Interaction {
  id: Int!
  creator: Creator!
  post: Post!
  text: String
  like: Boolean
  love: Boolean
  repost: Boolean
  share: Boolean
  createdAt: Date
  updatedAt: Date
}

type Post {
  id: Int!
  creator: Creator!
  published: Boolean
  interactions: [Interaction!]
  title: String!
  text: String
  status: String
  media: [String]
  tags: [String]
  createdAt: Date
  updatedAt: Date
}

type Template {
  id: Int!
  publisher: Creator!
  published: Boolean
  interactions: [Interaction!]
  title: String!
  code: String!
  tags: [String]
  createdAt: Date
  updatedAt: Date
}
