scalar Date

enum Permissions {
  READ
  WRITE
  LOGIN
  INTERACT
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
  PUBLISHED
  UNPUBLISHED
  DELTA
}

enum InteractionType {
  like
  love
  repost
  share
}

type Creator {
  id: Int!
  handle: String!
  verified: Boolean
  posts: [Post!]
  permissions: [Permissions!]
  interactions: [Interaction!]
  email: String!
  name: String!
  avatar: String!
  banner: String
  status: String
  bio: String
  website: String
  location: String
  birthday: String
  joined: String
  createdAt: Date
  updatedAt: Date
}

type Interaction {
  id: Int!
  creator: Creator!
  post: Post!
  text: String
  like: Boolean
  love: Boolean
  repost: Boolean
  share: Boolean
  createdAt: Date
  updatedAt: Date
}

type Post {
  id: Int!
  creator: Creator!
  published: Boolean
  interactions: [Interaction!]
  title: String!
  text: String
  status: String
  media: [String]
  tags: [String]
  createdAt: Date
  updatedAt: Date
}

type Query {
  creator(where: CreatorByInput, id: Int): Creator
  creators(where: CreatorByInput, by: ForOptionsInput): [Creator]
  interaction(where: InteractionByInput, id: Int): Interaction
  interactions(where: InteractionByInput, by: ForOptionsInput): [Interaction]
  post(where: PostByInput, id: Int): Post
  posts(where: PostByInput, by: ForOptionsInput): [Post]

  getPostInteractions(id: Int!): GetPostInteractionsPayload
  searchPosts(search: SearchPostsInput!, by: ForOptionsInput): SearchPostsPayload
}

type Mutation {
  createCreator(creator: CreateCreatorInput!): Creator!
  updateCreator(data: UpdateCreatorInput!, id: Int): Creator!
  deleteCreator(creatorId: Int, where: CreatorByInput): Creator!
  verifyCreator(id: Int!): Creator!
  unVerifyCreator(id: Int!): Creator!

  createInteraction(interaction: CreateInteractionInput!): Interaction!
  toggleInteraction(data: UpdateInteractionInput!, id: Int): Interaction!
  deleteInteraction(interactionId: Int, where: InteractionByInput): Interaction!

  createPost(post: CreatePostInput!): Post!
  updatePost(data: UpdatePostInput!, id: Int): Post!
  deletePost(id: Int, where: PostByInput): Post!
  publishPost(id: Int!): Post!
  unPublishPost(id: Int!): Post!
}

type Subscription {
  countdown(from: Int): Int!
  creator(where: CreatorByInput): CreatorSubscriptionPayload
  interaction(where: InteractionByInput): InteractionSubscriptionPayload
  interactionDelta(where: InteractionByInput): InteractionDeltaSubscriptionPayload
  post(where: PostByInput): PostSubscriptionPayload
}

input ForOptionsInput {
  take: Int
  skip: Int
  cursor: String
  orderById: String
}

type SearchPostsPayload {
  posts: [Post!]
}

type CreatorSubscriptionPayload {
  mutation: MutationType!
  data: Creator
}

type InteractionSubscriptionPayload {
  mutation: MutationType!
  data: Interaction
}

type InteractionDelta {
  id: Int!
  text: String
  like: Int!
  love: Int!
  share: Int!
  repost: Int!
}

type InteractionDeltaSubscriptionPayload {
  mutation: MutationType!
  data: InteractionDelta!
}

type PostSubscriptionPayload {
  mutation: MutationType!
  data: Post
}

type GetPostInteractionsPayload {
  likes: Int
  loves: Int
  reposts: Int
  shares: Int
}

input SearchPostsInput {
  text: String!
}

input CreatorByInput {
  email: String
  handle: String
  id: Int
  first: Int
  skip: Int
}

input InteractionByInput {
  creator: CreatorInput
  post: PostInput
  first: Int
  skip: Int
}

input PostByInput {
  id: Int
  creator: CreatorInput
  title: String
  first: Int
  skip: Int
}

input CreatorInput {
  id: Int
  handle: String
  email: String
}

input InteractionInput {
  id: Int
  post: PostInput
  creator: CreatorInput
}

input PostInput {
  id: Int
  title: String
  creator: CreatorInput
}

input CreateCreatorInput {
  name: String!
  handle: String!
  email: String!
  avatar: String
  banner: String
  verified: Boolean
}

input CreateInteractionInput {
  creatorId: Int!
  postId: Int!
  text: String
  like: Boolean
  love: Boolean
  repost: Boolean
  share: Boolean
}

input CreatePostInput {
  creatorId: Int!
  title: String!
  text: String
  published: Boolean
  status: String
  media: [String!]
}

input UpdateCreatorInput {
  email: String
  name: String
  avatar: String
  banner: String
  status: String
  bio: String
  website: String
  location: String
  birthday: String
}

input UpdateInteractionInput {
  creatorId: Int!
  postId: Int!
  text: String
  like: Boolean
  love: Boolean
  repost: Boolean
  share: Boolean
}

input UpdatePostInput {
  creatorId: Int!
  postId: Int!
  title: String
  text: String
  status: String
  media: [String!]
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
